// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdditionalContactList.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AdditionalContactList.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MMPro {
namespace micromsg {
class AdditionalContactListDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<AdditionalContactList> {
} _AdditionalContactList_default_instance_;

namespace protobuf_AdditionalContactList_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdditionalContactList, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdditionalContactList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdditionalContactList, _linkedincontactitem_),
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(AdditionalContactList)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_AdditionalContactList_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "AdditionalContactList.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _AdditionalContactList_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::MMPro::micromsg::protobuf_LinkedinContactItem_2eproto::InitDefaults();
  _AdditionalContactList_default_instance_.DefaultConstruct();
  _AdditionalContactList_default_instance_.get_mutable()->_linkedincontactitem_ = const_cast< ::MMPro::micromsg::LinkedinContactItem*>(
      ::MMPro::micromsg::LinkedinContactItem::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\033AdditionalContactList.proto\022\016MMPro.mic"
      "romsg\032\031LinkedinContactItem.proto\"Z\n\025Addi"
      "tionalContactList\022A\n\024_LinkedinContactIte"
      "m\030\001 \001(\0132#.MMPro.micromsg.LinkedinContact"
      "Item"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 164);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AdditionalContactList.proto", &protobuf_RegisterTypes);
  ::MMPro::micromsg::protobuf_LinkedinContactItem_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_AdditionalContactList_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AdditionalContactList::kLinkedinContactItemFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AdditionalContactList::AdditionalContactList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_AdditionalContactList_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MMPro.micromsg.AdditionalContactList)
}
AdditionalContactList::AdditionalContactList(const AdditionalContactList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has__linkedincontactitem()) {
    _linkedincontactitem_ = new ::MMPro::micromsg::LinkedinContactItem(*from._linkedincontactitem_);
  } else {
    _linkedincontactitem_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:MMPro.micromsg.AdditionalContactList)
}

void AdditionalContactList::SharedCtor() {
  _cached_size_ = 0;
  _linkedincontactitem_ = NULL;
}

AdditionalContactList::~AdditionalContactList() {
  // @@protoc_insertion_point(destructor:MMPro.micromsg.AdditionalContactList)
  SharedDtor();
}

void AdditionalContactList::SharedDtor() {
  if (this != internal_default_instance()) {
    delete _linkedincontactitem_;
  }
}

void AdditionalContactList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AdditionalContactList::descriptor() {
  protobuf_AdditionalContactList_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_AdditionalContactList_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AdditionalContactList& AdditionalContactList::default_instance() {
  protobuf_AdditionalContactList_2eproto::InitDefaults();
  return *internal_default_instance();
}

AdditionalContactList* AdditionalContactList::New(::google::protobuf::Arena* arena) const {
  AdditionalContactList* n = new AdditionalContactList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AdditionalContactList::Clear() {
// @@protoc_insertion_point(message_clear_start:MMPro.micromsg.AdditionalContactList)
  if (has__linkedincontactitem()) {
    GOOGLE_DCHECK(_linkedincontactitem_ != NULL);
    _linkedincontactitem_->::MMPro::micromsg::LinkedinContactItem::Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool AdditionalContactList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MMPro.micromsg.AdditionalContactList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MMPro.micromsg.LinkedinContactItem _LinkedinContactItem = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable__linkedincontactitem()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MMPro.micromsg.AdditionalContactList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MMPro.micromsg.AdditionalContactList)
  return false;
#undef DO_
}

void AdditionalContactList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MMPro.micromsg.AdditionalContactList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .MMPro.micromsg.LinkedinContactItem _LinkedinContactItem = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->_linkedincontactitem_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MMPro.micromsg.AdditionalContactList)
}

::google::protobuf::uint8* AdditionalContactList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MMPro.micromsg.AdditionalContactList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .MMPro.micromsg.LinkedinContactItem _LinkedinContactItem = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->_linkedincontactitem_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MMPro.micromsg.AdditionalContactList)
  return target;
}

size_t AdditionalContactList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MMPro.micromsg.AdditionalContactList)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // optional .MMPro.micromsg.LinkedinContactItem _LinkedinContactItem = 1;
  if (has__linkedincontactitem()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->_linkedincontactitem_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AdditionalContactList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MMPro.micromsg.AdditionalContactList)
  GOOGLE_DCHECK_NE(&from, this);
  const AdditionalContactList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AdditionalContactList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MMPro.micromsg.AdditionalContactList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MMPro.micromsg.AdditionalContactList)
    MergeFrom(*source);
  }
}

void AdditionalContactList::MergeFrom(const AdditionalContactList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MMPro.micromsg.AdditionalContactList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has__linkedincontactitem()) {
    mutable__linkedincontactitem()->::MMPro::micromsg::LinkedinContactItem::MergeFrom(from._linkedincontactitem());
  }
}

void AdditionalContactList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MMPro.micromsg.AdditionalContactList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AdditionalContactList::CopyFrom(const AdditionalContactList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MMPro.micromsg.AdditionalContactList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdditionalContactList::IsInitialized() const {
  return true;
}

void AdditionalContactList::Swap(AdditionalContactList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AdditionalContactList::InternalSwap(AdditionalContactList* other) {
  std::swap(_linkedincontactitem_, other->_linkedincontactitem_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AdditionalContactList::GetMetadata() const {
  protobuf_AdditionalContactList_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_AdditionalContactList_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AdditionalContactList

// optional .MMPro.micromsg.LinkedinContactItem _LinkedinContactItem = 1;
bool AdditionalContactList::has__linkedincontactitem() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void AdditionalContactList::set_has__linkedincontactitem() {
  _has_bits_[0] |= 0x00000001u;
}
void AdditionalContactList::clear_has__linkedincontactitem() {
  _has_bits_[0] &= ~0x00000001u;
}
void AdditionalContactList::clear__linkedincontactitem() {
  if (_linkedincontactitem_ != NULL) _linkedincontactitem_->::MMPro::micromsg::LinkedinContactItem::Clear();
  clear_has__linkedincontactitem();
}
const ::MMPro::micromsg::LinkedinContactItem& AdditionalContactList::_linkedincontactitem() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.AdditionalContactList._LinkedinContactItem)
  return _linkedincontactitem_ != NULL ? *_linkedincontactitem_
                         : *::MMPro::micromsg::LinkedinContactItem::internal_default_instance();
}
::MMPro::micromsg::LinkedinContactItem* AdditionalContactList::mutable__linkedincontactitem() {
  set_has__linkedincontactitem();
  if (_linkedincontactitem_ == NULL) {
    _linkedincontactitem_ = new ::MMPro::micromsg::LinkedinContactItem;
  }
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.AdditionalContactList._LinkedinContactItem)
  return _linkedincontactitem_;
}
::MMPro::micromsg::LinkedinContactItem* AdditionalContactList::release__linkedincontactitem() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.AdditionalContactList._LinkedinContactItem)
  clear_has__linkedincontactitem();
  ::MMPro::micromsg::LinkedinContactItem* temp = _linkedincontactitem_;
  _linkedincontactitem_ = NULL;
  return temp;
}
void AdditionalContactList::set_allocated__linkedincontactitem(::MMPro::micromsg::LinkedinContactItem* _linkedincontactitem) {
  delete _linkedincontactitem_;
  _linkedincontactitem_ = _linkedincontactitem;
  if (_linkedincontactitem) {
    set_has__linkedincontactitem();
  } else {
    clear_has__linkedincontactitem();
  }
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.AdditionalContactList._LinkedinContactItem)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)
