// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetContactLabelListResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GetContactLabelListResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MMPro {
namespace micromsg {
class GetContactLabelListResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<GetContactLabelListResponse> {
} _GetContactLabelListResponse_default_instance_;

namespace protobuf_GetContactLabelListResponse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetContactLabelListResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetContactLabelListResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetContactLabelListResponse, _baseresponse_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetContactLabelListResponse, _labelcount_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetContactLabelListResponse, _labelpairlist_),
  0,
  1,
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 8, sizeof(GetContactLabelListResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_GetContactLabelListResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "GetContactLabelListResponse.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _GetContactLabelListResponse_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::MMPro::micromsg::protobuf_BaseResponse_2eproto::InitDefaults();
  ::MMPro::micromsg::protobuf_LabelPair_2eproto::InitDefaults();
  _GetContactLabelListResponse_default_instance_.DefaultConstruct();
  _GetContactLabelListResponse_default_instance_.get_mutable()->_baseresponse_ = const_cast< ::MMPro::micromsg::BaseResponse*>(
      ::MMPro::micromsg::BaseResponse::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n!GetContactLabelListResponse.proto\022\016MMP"
      "ro.micromsg\032\022BaseResponse.proto\032\017LabelPa"
      "ir.proto\"\232\001\n\033GetContactLabelListResponse"
      "\0223\n\r_BaseResponse\030\001 \002(\0132\034.MMPro.micromsg"
      ".BaseResponse\022\023\n\013_LabelCount\030\002 \002(\r\0221\n\016_L"
      "abelPairList\030\003 \003(\0132\031.MMPro.micromsg.Labe"
      "lPair"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 245);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GetContactLabelListResponse.proto", &protobuf_RegisterTypes);
  ::MMPro::micromsg::protobuf_BaseResponse_2eproto::AddDescriptors();
  ::MMPro::micromsg::protobuf_LabelPair_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_GetContactLabelListResponse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetContactLabelListResponse::kBaseResponseFieldNumber;
const int GetContactLabelListResponse::kLabelCountFieldNumber;
const int GetContactLabelListResponse::kLabelPairListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetContactLabelListResponse::GetContactLabelListResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_GetContactLabelListResponse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MMPro.micromsg.GetContactLabelListResponse)
}
GetContactLabelListResponse::GetContactLabelListResponse(const GetContactLabelListResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      _labelpairlist_(from._labelpairlist_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has__baseresponse()) {
    _baseresponse_ = new ::MMPro::micromsg::BaseResponse(*from._baseresponse_);
  } else {
    _baseresponse_ = NULL;
  }
  _labelcount_ = from._labelcount_;
  // @@protoc_insertion_point(copy_constructor:MMPro.micromsg.GetContactLabelListResponse)
}

void GetContactLabelListResponse::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&_baseresponse_, 0, reinterpret_cast<char*>(&_labelcount_) -
    reinterpret_cast<char*>(&_baseresponse_) + sizeof(_labelcount_));
}

GetContactLabelListResponse::~GetContactLabelListResponse() {
  // @@protoc_insertion_point(destructor:MMPro.micromsg.GetContactLabelListResponse)
  SharedDtor();
}

void GetContactLabelListResponse::SharedDtor() {
  if (this != internal_default_instance()) {
    delete _baseresponse_;
  }
}

void GetContactLabelListResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetContactLabelListResponse::descriptor() {
  protobuf_GetContactLabelListResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GetContactLabelListResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetContactLabelListResponse& GetContactLabelListResponse::default_instance() {
  protobuf_GetContactLabelListResponse_2eproto::InitDefaults();
  return *internal_default_instance();
}

GetContactLabelListResponse* GetContactLabelListResponse::New(::google::protobuf::Arena* arena) const {
  GetContactLabelListResponse* n = new GetContactLabelListResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetContactLabelListResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MMPro.micromsg.GetContactLabelListResponse)
  _labelpairlist_.Clear();
  if (has__baseresponse()) {
    GOOGLE_DCHECK(_baseresponse_ != NULL);
    _baseresponse_->::MMPro::micromsg::BaseResponse::Clear();
  }
  _labelcount_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool GetContactLabelListResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MMPro.micromsg.GetContactLabelListResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable__baseresponse()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required uint32 _LabelCount = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has__labelcount();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_labelcount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .MMPro.micromsg.LabelPair _LabelPairList = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add__labelpairlist()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MMPro.micromsg.GetContactLabelListResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MMPro.micromsg.GetContactLabelListResponse)
  return false;
#undef DO_
}

void GetContactLabelListResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MMPro.micromsg.GetContactLabelListResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->_baseresponse_, output);
  }

  // required uint32 _LabelCount = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->_labelcount(), output);
  }

  // repeated .MMPro.micromsg.LabelPair _LabelPairList = 3;
  for (unsigned int i = 0, n = this->_labelpairlist_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_labelpairlist(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MMPro.micromsg.GetContactLabelListResponse)
}

::google::protobuf::uint8* GetContactLabelListResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MMPro.micromsg.GetContactLabelListResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->_baseresponse_, deterministic, target);
  }

  // required uint32 _LabelCount = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->_labelcount(), target);
  }

  // repeated .MMPro.micromsg.LabelPair _LabelPairList = 3;
  for (unsigned int i = 0, n = this->_labelpairlist_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->_labelpairlist(i), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MMPro.micromsg.GetContactLabelListResponse)
  return target;
}

size_t GetContactLabelListResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MMPro.micromsg.GetContactLabelListResponse)
  size_t total_size = 0;

  if (has__baseresponse()) {
    // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->_baseresponse_);
  }

  if (has__labelcount()) {
    // required uint32 _LabelCount = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_labelcount());
  }

  return total_size;
}
size_t GetContactLabelListResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MMPro.micromsg.GetContactLabelListResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->_baseresponse_);

    // required uint32 _LabelCount = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_labelcount());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated .MMPro.micromsg.LabelPair _LabelPairList = 3;
  {
    unsigned int count = this->_labelpairlist_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->_labelpairlist(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetContactLabelListResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MMPro.micromsg.GetContactLabelListResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetContactLabelListResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetContactLabelListResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MMPro.micromsg.GetContactLabelListResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MMPro.micromsg.GetContactLabelListResponse)
    MergeFrom(*source);
  }
}

void GetContactLabelListResponse::MergeFrom(const GetContactLabelListResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MMPro.micromsg.GetContactLabelListResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  _labelpairlist_.MergeFrom(from._labelpairlist_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable__baseresponse()->::MMPro::micromsg::BaseResponse::MergeFrom(from._baseresponse());
    }
    if (cached_has_bits & 0x00000002u) {
      _labelcount_ = from._labelcount_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void GetContactLabelListResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MMPro.micromsg.GetContactLabelListResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetContactLabelListResponse::CopyFrom(const GetContactLabelListResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MMPro.micromsg.GetContactLabelListResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetContactLabelListResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->_labelpairlist())) return false;
  if (has__baseresponse()) {
    if (!this->_baseresponse_->IsInitialized()) return false;
  }
  return true;
}

void GetContactLabelListResponse::Swap(GetContactLabelListResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetContactLabelListResponse::InternalSwap(GetContactLabelListResponse* other) {
  _labelpairlist_.InternalSwap(&other->_labelpairlist_);
  std::swap(_baseresponse_, other->_baseresponse_);
  std::swap(_labelcount_, other->_labelcount_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetContactLabelListResponse::GetMetadata() const {
  protobuf_GetContactLabelListResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GetContactLabelListResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetContactLabelListResponse

// required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
bool GetContactLabelListResponse::has__baseresponse() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void GetContactLabelListResponse::set_has__baseresponse() {
  _has_bits_[0] |= 0x00000001u;
}
void GetContactLabelListResponse::clear_has__baseresponse() {
  _has_bits_[0] &= ~0x00000001u;
}
void GetContactLabelListResponse::clear__baseresponse() {
  if (_baseresponse_ != NULL) _baseresponse_->::MMPro::micromsg::BaseResponse::Clear();
  clear_has__baseresponse();
}
const ::MMPro::micromsg::BaseResponse& GetContactLabelListResponse::_baseresponse() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.GetContactLabelListResponse._BaseResponse)
  return _baseresponse_ != NULL ? *_baseresponse_
                         : *::MMPro::micromsg::BaseResponse::internal_default_instance();
}
::MMPro::micromsg::BaseResponse* GetContactLabelListResponse::mutable__baseresponse() {
  set_has__baseresponse();
  if (_baseresponse_ == NULL) {
    _baseresponse_ = new ::MMPro::micromsg::BaseResponse;
  }
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.GetContactLabelListResponse._BaseResponse)
  return _baseresponse_;
}
::MMPro::micromsg::BaseResponse* GetContactLabelListResponse::release__baseresponse() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.GetContactLabelListResponse._BaseResponse)
  clear_has__baseresponse();
  ::MMPro::micromsg::BaseResponse* temp = _baseresponse_;
  _baseresponse_ = NULL;
  return temp;
}
void GetContactLabelListResponse::set_allocated__baseresponse(::MMPro::micromsg::BaseResponse* _baseresponse) {
  delete _baseresponse_;
  _baseresponse_ = _baseresponse;
  if (_baseresponse) {
    set_has__baseresponse();
  } else {
    clear_has__baseresponse();
  }
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.GetContactLabelListResponse._BaseResponse)
}

// required uint32 _LabelCount = 2;
bool GetContactLabelListResponse::has__labelcount() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void GetContactLabelListResponse::set_has__labelcount() {
  _has_bits_[0] |= 0x00000002u;
}
void GetContactLabelListResponse::clear_has__labelcount() {
  _has_bits_[0] &= ~0x00000002u;
}
void GetContactLabelListResponse::clear__labelcount() {
  _labelcount_ = 0u;
  clear_has__labelcount();
}
::google::protobuf::uint32 GetContactLabelListResponse::_labelcount() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.GetContactLabelListResponse._LabelCount)
  return _labelcount_;
}
void GetContactLabelListResponse::set__labelcount(::google::protobuf::uint32 value) {
  set_has__labelcount();
  _labelcount_ = value;
  // @@protoc_insertion_point(field_set:MMPro.micromsg.GetContactLabelListResponse._LabelCount)
}

// repeated .MMPro.micromsg.LabelPair _LabelPairList = 3;
int GetContactLabelListResponse::_labelpairlist_size() const {
  return _labelpairlist_.size();
}
void GetContactLabelListResponse::clear__labelpairlist() {
  _labelpairlist_.Clear();
}
const ::MMPro::micromsg::LabelPair& GetContactLabelListResponse::_labelpairlist(int index) const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.GetContactLabelListResponse._LabelPairList)
  return _labelpairlist_.Get(index);
}
::MMPro::micromsg::LabelPair* GetContactLabelListResponse::mutable__labelpairlist(int index) {
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.GetContactLabelListResponse._LabelPairList)
  return _labelpairlist_.Mutable(index);
}
::MMPro::micromsg::LabelPair* GetContactLabelListResponse::add__labelpairlist() {
  // @@protoc_insertion_point(field_add:MMPro.micromsg.GetContactLabelListResponse._LabelPairList)
  return _labelpairlist_.Add();
}
::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::LabelPair >*
GetContactLabelListResponse::mutable__labelpairlist() {
  // @@protoc_insertion_point(field_mutable_list:MMPro.micromsg.GetContactLabelListResponse._LabelPairList)
  return &_labelpairlist_;
}
const ::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::LabelPair >&
GetContactLabelListResponse::_labelpairlist() const {
  // @@protoc_insertion_point(field_list:MMPro.micromsg.GetContactLabelListResponse._LabelPairList)
  return _labelpairlist_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)
