// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SnsGroup.proto

#ifndef PROTOBUF_SnsGroup_2eproto__INCLUDED
#define PROTOBUF_SnsGroup_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace MMPro {
namespace micromsg {
class SnsGroup;
class SnsGroupDefaultTypeInternal;
extern SnsGroupDefaultTypeInternal _SnsGroup_default_instance_;
}  // namespace micromsg
}  // namespace MMPro

namespace MMPro {
namespace micromsg {

namespace protobuf_SnsGroup_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_SnsGroup_2eproto

// ===================================================================

class SnsGroup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MMPro.micromsg.SnsGroup) */ {
 public:
  SnsGroup();
  virtual ~SnsGroup();

  SnsGroup(const SnsGroup& from);

  inline SnsGroup& operator=(const SnsGroup& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SnsGroup& default_instance();

  static inline const SnsGroup* internal_default_instance() {
    return reinterpret_cast<const SnsGroup*>(
               &_SnsGroup_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SnsGroup* other);

  // implements Message ----------------------------------------------

  inline SnsGroup* New() const PROTOBUF_FINAL { return New(NULL); }

  SnsGroup* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SnsGroup& from);
  void MergeFrom(const SnsGroup& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SnsGroup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 _GroupId = 1;
  bool has__groupid() const;
  void clear__groupid();
  static const int kGroupIdFieldNumber = 1;
  ::google::protobuf::uint64 _groupid() const;
  void set__groupid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MMPro.micromsg.SnsGroup)
 private:
  void set_has__groupid();
  void clear_has__groupid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 _groupid_;
  friend struct protobuf_SnsGroup_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SnsGroup

// required uint64 _GroupId = 1;
inline bool SnsGroup::has__groupid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SnsGroup::set_has__groupid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SnsGroup::clear_has__groupid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SnsGroup::clear__groupid() {
  _groupid_ = GOOGLE_ULONGLONG(0);
  clear_has__groupid();
}
inline ::google::protobuf::uint64 SnsGroup::_groupid() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.SnsGroup._GroupId)
  return _groupid_;
}
inline void SnsGroup::set__groupid(::google::protobuf::uint64 value) {
  set_has__groupid();
  _groupid_ = value;
  // @@protoc_insertion_point(field_set:MMPro.micromsg.SnsGroup._GroupId)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SnsGroup_2eproto__INCLUDED
