// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SnsObjectDetailResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SnsObjectDetailResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MMPro {
namespace micromsg {
class SnsObjectDetailResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SnsObjectDetailResponse> {
} _SnsObjectDetailResponse_default_instance_;

namespace protobuf_SnsObjectDetailResponse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnsObjectDetailResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnsObjectDetailResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnsObjectDetailResponse, _baseresponse_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SnsObjectDetailResponse, _object_),
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(SnsObjectDetailResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SnsObjectDetailResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "SnsObjectDetailResponse.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _SnsObjectDetailResponse_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::MMPro::micromsg::protobuf_BaseResponse_2eproto::InitDefaults();
  ::MMPro::micromsg::protobuf_SnsObject_2eproto::InitDefaults();
  _SnsObjectDetailResponse_default_instance_.DefaultConstruct();
  _SnsObjectDetailResponse_default_instance_.get_mutable()->_baseresponse_ = const_cast< ::MMPro::micromsg::BaseResponse*>(
      ::MMPro::micromsg::BaseResponse::internal_default_instance());
  _SnsObjectDetailResponse_default_instance_.get_mutable()->_object_ = const_cast< ::MMPro::micromsg::SnsObject*>(
      ::MMPro::micromsg::SnsObject::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\035SnsObjectDetailResponse.proto\022\016MMPro.m"
      "icromsg\032\022BaseResponse.proto\032\017SnsObject.p"
      "roto\"z\n\027SnsObjectDetailResponse\0223\n\r_Base"
      "Response\030\001 \002(\0132\034.MMPro.micromsg.BaseResp"
      "onse\022*\n\007_Object\030\002 \002(\0132\031.MMPro.micromsg.S"
      "nsObject"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 208);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SnsObjectDetailResponse.proto", &protobuf_RegisterTypes);
  ::MMPro::micromsg::protobuf_BaseResponse_2eproto::AddDescriptors();
  ::MMPro::micromsg::protobuf_SnsObject_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_SnsObjectDetailResponse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SnsObjectDetailResponse::kBaseResponseFieldNumber;
const int SnsObjectDetailResponse::kObjectFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SnsObjectDetailResponse::SnsObjectDetailResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_SnsObjectDetailResponse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MMPro.micromsg.SnsObjectDetailResponse)
}
SnsObjectDetailResponse::SnsObjectDetailResponse(const SnsObjectDetailResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has__baseresponse()) {
    _baseresponse_ = new ::MMPro::micromsg::BaseResponse(*from._baseresponse_);
  } else {
    _baseresponse_ = NULL;
  }
  if (from.has__object()) {
    _object_ = new ::MMPro::micromsg::SnsObject(*from._object_);
  } else {
    _object_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:MMPro.micromsg.SnsObjectDetailResponse)
}

void SnsObjectDetailResponse::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&_baseresponse_, 0, reinterpret_cast<char*>(&_object_) -
    reinterpret_cast<char*>(&_baseresponse_) + sizeof(_object_));
}

SnsObjectDetailResponse::~SnsObjectDetailResponse() {
  // @@protoc_insertion_point(destructor:MMPro.micromsg.SnsObjectDetailResponse)
  SharedDtor();
}

void SnsObjectDetailResponse::SharedDtor() {
  if (this != internal_default_instance()) {
    delete _baseresponse_;
  }
  if (this != internal_default_instance()) {
    delete _object_;
  }
}

void SnsObjectDetailResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SnsObjectDetailResponse::descriptor() {
  protobuf_SnsObjectDetailResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_SnsObjectDetailResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SnsObjectDetailResponse& SnsObjectDetailResponse::default_instance() {
  protobuf_SnsObjectDetailResponse_2eproto::InitDefaults();
  return *internal_default_instance();
}

SnsObjectDetailResponse* SnsObjectDetailResponse::New(::google::protobuf::Arena* arena) const {
  SnsObjectDetailResponse* n = new SnsObjectDetailResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SnsObjectDetailResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MMPro.micromsg.SnsObjectDetailResponse)
  if (_has_bits_[0 / 32] & 3u) {
    if (has__baseresponse()) {
      GOOGLE_DCHECK(_baseresponse_ != NULL);
      _baseresponse_->::MMPro::micromsg::BaseResponse::Clear();
    }
    if (has__object()) {
      GOOGLE_DCHECK(_object_ != NULL);
      _object_->::MMPro::micromsg::SnsObject::Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SnsObjectDetailResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MMPro.micromsg.SnsObjectDetailResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable__baseresponse()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .MMPro.micromsg.SnsObject _Object = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable__object()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MMPro.micromsg.SnsObjectDetailResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MMPro.micromsg.SnsObjectDetailResponse)
  return false;
#undef DO_
}

void SnsObjectDetailResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MMPro.micromsg.SnsObjectDetailResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->_baseresponse_, output);
  }

  // required .MMPro.micromsg.SnsObject _Object = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->_object_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MMPro.micromsg.SnsObjectDetailResponse)
}

::google::protobuf::uint8* SnsObjectDetailResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MMPro.micromsg.SnsObjectDetailResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->_baseresponse_, deterministic, target);
  }

  // required .MMPro.micromsg.SnsObject _Object = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->_object_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MMPro.micromsg.SnsObjectDetailResponse)
  return target;
}

size_t SnsObjectDetailResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MMPro.micromsg.SnsObjectDetailResponse)
  size_t total_size = 0;

  if (has__baseresponse()) {
    // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->_baseresponse_);
  }

  if (has__object()) {
    // required .MMPro.micromsg.SnsObject _Object = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->_object_);
  }

  return total_size;
}
size_t SnsObjectDetailResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MMPro.micromsg.SnsObjectDetailResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->_baseresponse_);

    // required .MMPro.micromsg.SnsObject _Object = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->_object_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SnsObjectDetailResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MMPro.micromsg.SnsObjectDetailResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const SnsObjectDetailResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SnsObjectDetailResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MMPro.micromsg.SnsObjectDetailResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MMPro.micromsg.SnsObjectDetailResponse)
    MergeFrom(*source);
  }
}

void SnsObjectDetailResponse::MergeFrom(const SnsObjectDetailResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MMPro.micromsg.SnsObjectDetailResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable__baseresponse()->::MMPro::micromsg::BaseResponse::MergeFrom(from._baseresponse());
    }
    if (cached_has_bits & 0x00000002u) {
      mutable__object()->::MMPro::micromsg::SnsObject::MergeFrom(from._object());
    }
  }
}

void SnsObjectDetailResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MMPro.micromsg.SnsObjectDetailResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SnsObjectDetailResponse::CopyFrom(const SnsObjectDetailResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MMPro.micromsg.SnsObjectDetailResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SnsObjectDetailResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  if (has__baseresponse()) {
    if (!this->_baseresponse_->IsInitialized()) return false;
  }
  if (has__object()) {
    if (!this->_object_->IsInitialized()) return false;
  }
  return true;
}

void SnsObjectDetailResponse::Swap(SnsObjectDetailResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SnsObjectDetailResponse::InternalSwap(SnsObjectDetailResponse* other) {
  std::swap(_baseresponse_, other->_baseresponse_);
  std::swap(_object_, other->_object_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SnsObjectDetailResponse::GetMetadata() const {
  protobuf_SnsObjectDetailResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_SnsObjectDetailResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SnsObjectDetailResponse

// required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
bool SnsObjectDetailResponse::has__baseresponse() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SnsObjectDetailResponse::set_has__baseresponse() {
  _has_bits_[0] |= 0x00000001u;
}
void SnsObjectDetailResponse::clear_has__baseresponse() {
  _has_bits_[0] &= ~0x00000001u;
}
void SnsObjectDetailResponse::clear__baseresponse() {
  if (_baseresponse_ != NULL) _baseresponse_->::MMPro::micromsg::BaseResponse::Clear();
  clear_has__baseresponse();
}
const ::MMPro::micromsg::BaseResponse& SnsObjectDetailResponse::_baseresponse() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.SnsObjectDetailResponse._BaseResponse)
  return _baseresponse_ != NULL ? *_baseresponse_
                         : *::MMPro::micromsg::BaseResponse::internal_default_instance();
}
::MMPro::micromsg::BaseResponse* SnsObjectDetailResponse::mutable__baseresponse() {
  set_has__baseresponse();
  if (_baseresponse_ == NULL) {
    _baseresponse_ = new ::MMPro::micromsg::BaseResponse;
  }
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.SnsObjectDetailResponse._BaseResponse)
  return _baseresponse_;
}
::MMPro::micromsg::BaseResponse* SnsObjectDetailResponse::release__baseresponse() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.SnsObjectDetailResponse._BaseResponse)
  clear_has__baseresponse();
  ::MMPro::micromsg::BaseResponse* temp = _baseresponse_;
  _baseresponse_ = NULL;
  return temp;
}
void SnsObjectDetailResponse::set_allocated__baseresponse(::MMPro::micromsg::BaseResponse* _baseresponse) {
  delete _baseresponse_;
  _baseresponse_ = _baseresponse;
  if (_baseresponse) {
    set_has__baseresponse();
  } else {
    clear_has__baseresponse();
  }
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.SnsObjectDetailResponse._BaseResponse)
}

// required .MMPro.micromsg.SnsObject _Object = 2;
bool SnsObjectDetailResponse::has__object() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void SnsObjectDetailResponse::set_has__object() {
  _has_bits_[0] |= 0x00000002u;
}
void SnsObjectDetailResponse::clear_has__object() {
  _has_bits_[0] &= ~0x00000002u;
}
void SnsObjectDetailResponse::clear__object() {
  if (_object_ != NULL) _object_->::MMPro::micromsg::SnsObject::Clear();
  clear_has__object();
}
const ::MMPro::micromsg::SnsObject& SnsObjectDetailResponse::_object() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.SnsObjectDetailResponse._Object)
  return _object_ != NULL ? *_object_
                         : *::MMPro::micromsg::SnsObject::internal_default_instance();
}
::MMPro::micromsg::SnsObject* SnsObjectDetailResponse::mutable__object() {
  set_has__object();
  if (_object_ == NULL) {
    _object_ = new ::MMPro::micromsg::SnsObject;
  }
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.SnsObjectDetailResponse._Object)
  return _object_;
}
::MMPro::micromsg::SnsObject* SnsObjectDetailResponse::release__object() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.SnsObjectDetailResponse._Object)
  clear_has__object();
  ::MMPro::micromsg::SnsObject* temp = _object_;
  _object_ = NULL;
  return temp;
}
void SnsObjectDetailResponse::set_allocated__object(::MMPro::micromsg::SnsObject* _object) {
  delete _object_;
  _object_ = _object;
  if (_object) {
    set_has__object();
  } else {
    clear_has__object();
  }
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.SnsObjectDetailResponse._Object)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)
